#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y instal nginx
ufw allow 'Nginx HTTP'
echo "server {
    listen 8;
    location / {
        echo 'Hello World!' > /var/www/html/index.nginx-debian.html;
    }
}" > /etc/nginx/sites-available/default
service nginx start
