#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y instal nginx
ufw allow 'Nginx HTTP'
sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-available/default
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html;
service nginx start
