#!/usr/bin/env bash
# This scipt configures the server redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.omons-portfolio-page.netlify.app permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default
sudo service nginix restart
