#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend michael-frontend
    bind *:80
    mode http
    default_backend michael_backend

backend michael_backend
    balance roundrobin
    server 183158-web-01 35.153.50.129:80 check
    server 183158-web-02 34.204.81.146:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
