#!/usr/bin/env bash
# When passing the argument start:
#       Starts manage_my_process
#       Creates a file containing its PID in /var/run/my_process.pid
#       Displays manage_my_process started
#+  When passing the argument stop:
#       Stops manage_my_process
#       Deletes the file /var/run/my_process.pid
#       Displays manage_my_process stopped
#+  When passing the argument restart
#       Stops manage_my_process
#       Deletes the file /var/run/my_process.pid
#       Starts manage_my_process
#       Creates a file containing its PID in /var/run/my_process.pid
#       Displays manage_my_process restarted
#+  Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

FILE="/var/run/my_process.pid"
start() {
    sudo ./manage_my_process &
    touch "$FILE"
    echo "$!" > "$FILE"    
    echo "manage_my_process started"
}

stop() {
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
}

restart() {
    kill "$(cat /var/run/my_process.pid)"
    rm "$FILE"
    sudo ./manage_my_process &
    touch "$FILE"
    echo "$!" > "$FILE"
    echo "manage_my_process restarted"
}

case "${1}" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

