#!/usr/bin/env bash
# This Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

LOOP=0
while [ "$LOOP" -ne 1 ]; do
    echo "To infinity and beyond"
    sleep 2
done
