#!/usr/bin/env bash
# This Bash script that displays the time for 12 hours and 59 minutes:
#  display hours from 0 to 12
#  display minutes from 1 to 59

HOUR=0
while [ "$HOUR" -le 12 ]; do
    echo "Hour: $HOUR"

    MINS=1
    while [ $MINS -lt 60 ]; do
        echo "$MINS"

        MINS=$((MINS + 1))
    done

    HOUR=$((HOUR + 1))
done
