#!/usr/bin/env bash
# This Bash script that displays the content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

LIST=$(ls)
for FILE in $LIST; do
    echo "$FILE" | cut -d '-' -f2
done
