#!/usr/bin/env bash
# Configures on Ubuntu server with the following requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com reolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2    localhost" > /etc/hosts.new
echo "8.8.8.8  facebook.com" >> /etc/hosts.new
cp -f ~/host.new /etc/hosts
