#!/usr/bin/env bash
# Configures my local SSH client to connect to a server without typing a password
Host *
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredential no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
